const fs = require('fs');
const content = fs.readFileSync('artifacts/erkan-ai/src/lib/i18n.tsx', 'utf8');

const additions = {
  syrian: '    themeTitle: "تخصيص المظهر",\n    themeSub: "غير الألوان والشكل",\n    themeDesc: "اختار المظهر اللي بيناسبك أو صمم مظهر خاص فيك",\n    themeDark: "داكن",\n    themeAmoled: "أسود AMOLED",\n    themeLight: "فاتح",\n    themePurple: "بنفسجي",\n    themeBlue: "أزرق",\n    themeCyan: "سماوي",\n    themeGreen: "أخضر",\n    themeEmerald: "زمردي",\n    themeYellow: "أصفر",\n    themeOrange: "برتقالي",\n    themeRed: "أحمر",\n    themePink: "زهري",\n    themeRose: "وردي",\n    themeCustom: "مخصص",\n    themeCustomTitle: "تخصيص الألوان",\n    customBg: "الخلفية",\n    customPrimary: "اللون الأساسي",\n    customSecondary: "اللون الثانوي",\n    customSurface: "لون البطاقات",\n    customText: "النص الأساسي",\n    customTextMuted: "النص الباهت",\n    themeCustomWarning: "انتبه: الألوان المخصصة ممكن تأثر على وضوح القراءة. جرب الألوان الفاتحة مع خلفية غامقة.",\n    comingSoon: "هالميزة جاية قريباً!",\n    menuCamera: "كاميرا",\n    menuGallery: "معرض الصور",\n    menuDocs: "مستندات",\n    menuPDF: "ملفات PDF",\n    menuAudio: "صوتيات",\n    menuVideo: "فيديو",\n    menuPhoto: "التقاط صورة",\n    menuGenImg: "توليد صورة بالذكاء",\n    menuAnalyzeImg: "تحليل صورة",\n    menuAnalyzeFile: "تحليل ملف",\n    menuOCR: "استخراج النص",\n    menuQR: "مسح QR",\n    menuTranslate: "ترجمة",\n    menuCode: "محرر أكواد",\n    menuNotes: "ملاحظات",\n    menuCalc: "حاسبة",\n    menuCalendar: "تقويم",\n    menuContacts: "جهات الاتصال",\n    menuLocation: "الموقع",\n    menuWeb: "بحث ويب",\n    menuVoice: "تسجيل صوتي",\n    menuTable: "إنشاء جدول",\n    menuChart: "إنشاء رسم بياني",\n    menuDraw: "رسم",\n    menuMore: "المزيد",',
  egyptian: '    themeTitle: "تخصيص المظهر",\n    themeSub: "غير الألوان والشكل",\n    themeDesc: "اختار المظهر اللي يناسبك أو صمم مظهر خاص بيك",\n    themeDark: "داكن",\n    themeAmoled: "أسود AMOLED",\n    themeLight: "فاتح",\n    themePurple: "بنفسجي",\n    themeBlue: "أزرق",\n    themeCyan: "سماوي",\n    themeGreen: "أخضر",\n    themeEmerald: "زمردي",\n    themeYellow: "أصفر",\n    themeOrange: "برتقالي",\n    themeRed: "أحمر",\n    themePink: "بمبي",\n    themeRose: "وردي",\n    themeCustom: "مخصص",\n    themeCustomTitle: "تخصيص الألوان",\n    customBg: "الخلفية",\n    customPrimary: "اللون الأساسي",\n    customSecondary: "اللون الثانوي",\n    customSurface: "لون البطاقات",\n    customText: "النص الأساسي",\n    customTextMuted: "النص الباهت",\n    themeCustomWarning: "خلي بالك: الألوان المخصصة ممكن تأثر على وضوح القراءة. جرب الألوان الفاتحة مع خلفية غامقة.",\n    comingSoon: "الميزة دي جاية قريب!",\n    menuCamera: "كاميرا",\n    menuGallery: "معرض الصور",\n    menuDocs: "مستندات",\n    menuPDF: "ملفات PDF",\n    menuAudio: "صوتيات",\n    menuVideo: "فيديو",\n    menuPhoto: "التقاط صورة",\n    menuGenImg: "توليد صورة بالذكاء",\n    menuAnalyzeImg: "تحليل صورة",\n    menuAnalyzeFile: "تحليل ملف",\n    menuOCR: "استخراج النص",\n    menuQR: "مسح QR",\n    menuTranslate: "ترجمة",\n    menuCode: "محرر أكواد",\n    menuNotes: "ملاحظات",\n    menuCalc: "حاسبة",\n    menuCalendar: "نتيجة",\n    menuContacts: "جهات الاتصال",\n    menuLocation: "الموقع",\n    menuWeb: "بحث ويب",\n    menuVoice: "تسجيل صوتي",\n    menuTable: "إنشاء جدول",\n    menuChart: "إنشاء رسم بياني",\n    menuDraw: "رسم",\n    menuMore: "المزيد",',
  saudi: '    themeTitle: "تخصيص المظهر",\n    themeSub: "غير الألوان والشكل",\n    themeDesc: "اختر المظهر اللي يناسبك أو صمم مظهر خاص فيك",\n    themeDark: "داكن",\n    themeAmoled: "أسود AMOLED",\n    themeLight: "فاتح",\n    themePurple: "بنفسجي",\n    themeBlue: "أزرق",\n    themeCyan: "سماوي",\n    themeGreen: "أخضر",\n    themeEmerald: "زمردي",\n    themeYellow: "أصفر",\n    themeOrange: "برتقالي",\n    themeRed: "أحمر",\n    themePink: "وردي",\n    themeRose: "زهري",\n    themeCustom: "مخصص",\n    themeCustomTitle: "تخصيص الألوان",\n    customBg: "الخلفية",\n    customPrimary: "اللون الأساسي",\n    customSecondary: "اللون الثانوي",\n    customSurface: "لون البطاقات",\n    customText: "النص الأساسي",\n    customTextMuted: "النص الباهت",\n    themeCustomWarning: "تنبيه: الألوان المخصصة ممكن تأثر على وضوح القراءة. جرب الألوان الفاتحة مع خلفية غامقة.",\n    comingSoon: "هالميزة جاية قريب!",\n    menuCamera: "كاميرا",\n    menuGallery: "معرض الصور",\n    menuDocs: "مستندات",\n    menuPDF: "ملفات PDF",\n    menuAudio: "صوتيات",\n    menuVideo: "فيديو",\n    menuPhoto: "التقاط صورة",\n    menuGenImg: "توليد صورة بالذكاء",\n    menuAnalyzeImg: "تحليل صورة",\n    menuAnalyzeFile: "تحليل ملف",\n    menuOCR: "استخراج النص",\n    menuQR: "مسح QR",\n    menuTranslate: "ترجمة",\n    menuCode: "محرر أكواد",\n    menuNotes: "ملاحظات",\n    menuCalc: "حاسبة",\n    menuCalendar: "تقويم",\n    menuContacts: "جهات الاتصال",\n    menuLocation: "الموقع",\n    menuWeb: "بحث ويب",\n    menuVoice: "تسجيل صوتي",\n    menuTable: "إنشاء جدول",\n    menuChart: "إنشاء رسم بياني",\n    menuDraw: "رسم",\n    menuMore: "المزيد",',
  jordanian: '    themeTitle: "تخصيص المظهر",\n    themeSub: "غير الألوان والشكل",\n    themeDesc: "اختار المظهر اللي بيناسبك أو صمم مظهر خاص إلك",\n    themeDark: "داكن",\n    themeAmoled: "أسود AMOLED",\n    themeLight: "فاتح",\n    themePurple: "بنفسجي",\n    themeBlue: "أزرق",\n    themeCyan: "سماوي",\n    themeGreen: "أخضر",\n    themeEmerald: "زمردي",\n    themeYellow: "أصفر",\n    themeOrange: "برتقالي",\n    themeRed: "أحمر",\n    themePink: "زهري",\n    themeRose: "وردي",\n    themeCustom: "مخصص",\n    themeCustomTitle: "تخصيص الألوان",\n    customBg: "الخلفية",\n    customPrimary: "اللون الأساسي",\n    customSecondary: "اللون الثانوي",\n    customSurface: "لون البطاقات",\n    customText: "النص الأساسي",\n    customTextMuted: "النص الباهت",\n    themeCustomWarning: "انتبه: الألوان المخصصة ممكن تأثر على وضوح القراءة. جرب الألوان الفاتحة مع خلفية غامقة.",\n    comingSoon: "هالميزة جاية قريباً!",\n    menuCamera: "كاميرا",\n    menuGallery: "معرض الصور",\n    menuDocs: "مستندات",\n    menuPDF: "ملفات PDF",\n    menuAudio: "صوتيات",\n    menuVideo: "فيديو",\n    menuPhoto: "التقاط صورة",\n    menuGenImg: "توليد صورة بالذكاء",\n    menuAnalyzeImg: "تحليل صورة",\n    menuAnalyzeFile: "تحليل ملف",\n    menuOCR: "استخراج النص",\n    menuQR: "مسح QR",\n    menuTranslate: "ترجمة",\n    menuCode: "محرر أكواد",\n    menuNotes: "ملاحظات",\n    menuCalc: "حاسبة",\n    menuCalendar: "تقويم",\n    menuContacts: "جهات الاتصال",\n    menuLocation: "الموقع",\n    menuWeb: "بحث ويب",\n    menuVoice: "تسجيل صوتي",\n    menuTable: "إنشاء جدول",\n    menuChart: "إنشاء رسم بياني",\n    menuDraw: "رسم",\n    menuMore: "المزيد",',
  turkish: '    themeTitle: "Görünümü Özelleştir",\n    themeSub: "Renkleri ve temayı değiştir",\n    themeDesc: "Size uygun temayı seçin veya kendi temanızı tasarlayın",\n    themeDark: "Karanlık",\n    themeAmoled: "AMOLED Siyahı",\n    themeLight: "Aydınlık",\n    themePurple: "Mor",\n    themeBlue: "Mavi",\n    themeCyan: "Cam Göbeği",\n    themeGreen: "Yeşil",\n    themeEmerald: "Zümrüt",\n    themeYellow: "Sarı",\n    themeOrange: "Turuncu",\n    themeRed: "Kırmızı",\n    themePink: "Pembe",\n    themeRose: "Gül",\n    themeCustom: "Özel",\n    themeCustomTitle: "Renkleri Özelleştir",\n    customBg: "Arka Plan",\n    customPrimary: "Birincil Renk",\n    customSecondary: "İkincil Renk",\n    customSurface: "Kart Rengi",\n    customText: "Ana Metin",\n    customTextMuted: "Soluk Metin",\n    themeCustomWarning: "Uyarı: Özel renkler okunabilirliği etkileyebilir. Koyu arka planla açık renkler deneyin.",\n    comingSoon: "Bu özellik yakında geliyor!",\n    menuCamera: "Kamera",\n    menuGallery: "Galeri",\n    menuDocs: "Belgeler",\n    menuPDF: "PDF Dosyaları",\n    menuAudio: "Sesler",\n    menuVideo: "Video",\n    menuPhoto: "Fotoğraf Çek",\n    menuGenImg: "Yapay Zeka ile Görsel Üret",\n    menuAnalyzeImg: "Görsel Analizi",\n    menuAnalyzeFile: "Dosya Analizi",\n    menuOCR: "Metin Çıkar",\n    menuQR: "QR Tara",\n    menuTranslate: "Çeviri",\n    menuCode: "Kod Editörü",\n    menuNotes: "Notlar",\n    menuCalc: "Hesap Makinesi",\n    menuCalendar: "Takvim",\n    menuContacts: "Kişiler",\n    menuLocation: "Konum",\n    menuWeb: "Web Arama",\n    menuVoice: "Ses Kaydı",\n    menuTable: "Tablo Oluştur",\n    menuChart: "Grafik Oluştur",\n    menuDraw: "Çizim",\n    menuMore: "Daha Fazla",'
};

let newContent = content;
const keys = ['syrian', 'egyptian', 'saudi', 'jordanian', 'turkish'];

for (const key of keys) {
  const marker = key + ": {";
  const parts = newContent.split(marker);
  if (parts.length > 1) {
    let section = parts[1];
    const indexOfSub = section.indexOf("langMenuSub:");
    if (indexOfSub > -1) {
      const endOfLine = section.indexOf("\\n", indexOfSub);
      section = section.slice(0, endOfLine + 1) + additions[key] + "\\n" + section.slice(endOfLine + 1);
      parts[1] = section;
      newContent = parts.join(marker);
    }
  }
}

fs.writeFileSync('artifacts/erkan-ai/src/lib/i18n.tsx', newContent);
console.log('done');
