import { useFocusEffect, useRouter } from 'expo-router';
import React, { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { useAuth } from '@/contexts/AuthContext';
import { cancelSubscription, extendSubscription, getMe, getSubscriptionStatus, getWallet, transferSubscription, type MobileUser, type SubscriptionStatus, type WalletSummary, type SubscriptionExtensionResult, type SubscriptionCancelResult, type SubscriptionTransferResult } from '@/lib/mobile-api';
import { GlowCard, Pill, PrimaryButton, ScreenBackground, SectionLabel, TopBar } from '@/components/MobileChrome';
import colors from '@/constants/colors';

const targets = [30, 60, 90] as const;
const dailyPrices = { pro: 50, pro_max: 120 } as const;
type Action = 'extend' | 'cancel' | 'transfer' | null;
type Notice = { type: 'success' | 'error'; text: string } | null;

function planLabel(plan: string) { return plan === 'pro_max' ? 'مطنوخ' : plan === 'pro' ? 'على البركة' : 'درويش'; }
function planTone(plan: string): 'blue' | 'purple' | 'green' { return plan === 'pro_max' ? 'purple' : plan === 'pro' ? 'blue' : 'green'; }
function remainingDays(expiresAt: string | null) { return expiresAt ? Math.max(0, Math.ceil((new Date(expiresAt).getTime() - Date.now()) / 86400000)) : 0; }
function money(value: number) { return `${Math.max(0, Math.round(value)).toLocaleString('en-US')} EKN`; }
function date(value: string | null) { return value ? new Date(value).toLocaleDateString('ar-EG') : 'لا يوجد اشتراك مدفوع'; }

export default function SubscriptionManagementScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const { user, updateUser } = useAuth();
  const [profile, setProfile] = useState<MobileUser | null>(user); const [status, setStatus] = useState<SubscriptionStatus | null>(null); const [wallet, setWallet] = useState<WalletSummary | null>(null);
  const [selectedTarget, setSelectedTarget] = useState<(typeof targets)[number]>(30); const [recipient, setRecipient] = useState('');
  const [transferVisible, setTransferVisible] = useState(false); const [action, setAction] = useState<Action>(null); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(''); const [notice, setNotice] = useState<Notice>(null);
  const [extensionResult, setExtensionResult] = useState<SubscriptionExtensionResult | null>(null); const [cancelResult, setCancelResult] = useState<SubscriptionCancelResult | null>(null); const [transferResult, setTransferResult] = useState<SubscriptionTransferResult | null>(null);
  const load = useCallback(async () => { setLoading(true); setLoadError(''); try { const [p, s, w] = await Promise.all([getMe(), getSubscriptionStatus(), getWallet()]); setProfile(p); setStatus(s); setWallet(w); updateUser(p); } catch (e) { setLoadError(e instanceof Error ? e.message : 'حاول مرة أخرى.'); } finally { setLoading(false); } }, [updateUser]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const plan = status?.plan ?? profile?.subscriptionType ?? 'free'; const isPaid = plan === 'pro' || plan === 'pro_max'; const days = remainingDays(status?.expiresAt ?? profile?.subscriptionExpiresAt ?? null);
  const rate = isPaid ? dailyPrices[plan as 'pro' | 'pro_max'] : 0; const extensionDays = Math.max(0, selectedTarget - days); const extensionCost = extensionDays * rate; const balanceAfter = (wallet?.balance ?? 0) - extensionCost; const targetReached = isPaid && days >= selectedTarget;
  const normalizedRecipient = recipient.trim().toUpperCase(); const validRecipient = /^LMR-\d+$/.test(normalizedRecipient);
  const clearResults = () => { setNotice(null); setExtensionResult(null); setCancelResult(null); setTransferResult(null); };
  const execute = async () => {
    if (!action || (action === 'extend' && (!isPaid || extensionDays < 1 || balanceAfter < 0)) || (action === 'transfer' && !validRecipient)) return;
    setBusy(true); setNotice(null);
    try {
      if (action === 'extend') { const result = await extendSubscription(extensionDays); setExtensionResult(result); setWallet(w => w ? { ...w, balance: result.balance } : w); setNotice({ type: 'success', text: `تم تمديد اشتراكك وإضافة ${result.additionalDays} يوم` }); }
      else if (action === 'cancel') { const result = await cancelSubscription(); setCancelResult(result); setNotice({ type: 'success', text: 'تم إلغاء الاشتراك فوراً' }); }
      else { const result = await transferSubscription(normalizedRecipient); setTransferResult(result); setRecipient(''); setTransferVisible(false); setNotice({ type: 'success', text: 'تم نقل الاشتراك بنجاح' }); }
      setAction(null); await load();
    } catch (e) { setNotice({ type: 'error', text: e instanceof Error ? e.message : 'تعذر تنفيذ العملية.' }); }
    finally { setBusy(false); }
  };
  const reviewTransfer = () => { if (!validRecipient) { setNotice({ type: 'error', text: 'أدخل معرّف LMR صحيحاً مثل LMR-123456' }); return; } setTransferVisible(false); setAction('transfer'); };
  const modalTitle = action === 'extend' ? 'تأكيد تمديد الاشتراك' : action === 'cancel' ? 'تأكيد الإلغاء الفوري' : 'تأكيد نقل الاشتراك';
  const modalDescription = action === 'extend' ? `سيتم خصم ${money(extensionCost)} وإضافة ${extensionDays} يوم إلى الاشتراك.` : action === 'cancel' ? 'سيُلغى اشتراكك فوراً وستفقد مزايا الخطة المدفوعة. لا يمكن التراجع عن هذا الإجراء.' : `سيُنقل اشتراكك النشط بالكامل إلى الحساب ${normalizedRecipient}. لن يبقى الاشتراك على حسابك الحالي.`;

  if (loading && !status) return <ScreenBackground><View style={styles.loading}><ActivityIndicator color={colors.light.primary} size="large" /><Text style={styles.loadingText}>جاري تحميل تفاصيل الاشتراك...</Text></View></ScreenBackground>;
  return <ScreenBackground><ScrollView contentContainerStyle={{ paddingTop: insets.top + 12, paddingBottom: insets.bottom + 32 }} keyboardShouldPersistTaps="handled">
    <TopBar title="إدارة الاشتراك" subtitle="تحكم كامل بخطتك من حسابك" />
    {notice && <View style={[styles.notice, notice.type === 'error' && styles.noticeError]}><Feather name={notice.type === 'success' ? 'check-circle' : 'alert-triangle'} size={17} color={notice.type === 'success' ? colors.light.success : colors.light.destructive} /><Text style={styles.noticeText}>{notice.text}</Text><Pressable onPress={() => setNotice(null)}><Feather name="x" size={16} color={colors.light.mutedForeground} /></Pressable></View>}
    {loadError ? <View style={styles.errorCard}><Feather name="alert-triangle" size={25} color={colors.light.destructive} /><Text style={styles.errorTitle}>تعذر تحميل بيانات الاشتراك</Text><Text style={styles.errorText}>{loadError}</Text><PrimaryButton secondary onPress={() => void load()}>إعادة المحاولة</PrimaryButton></View> : <>
      <GlowCard accent={plan === 'pro_max' ? 'purple' : plan === 'pro' ? 'blue' : 'teal'} style={styles.heroCard}>
        <View style={styles.heroTop}><Pill tone={planTone(plan)}>{planLabel(plan)}</Pill><View style={styles.heroIcon}><Feather name={isPaid ? 'award' : 'zap'} size={20} color="#c9d8ff" /></View></View>
        <Text style={styles.heroTitle}>{isPaid ? 'اشتراكك فعال' : 'أنت على الخطة المجانية'}</Text><Text style={styles.heroText}>{isPaid ? `متبقي تقريبًا ${days} يومًا • ينتهي في ${date(status?.expiresAt ?? profile?.subscriptionExpiresAt ?? null)}` : 'فعّل خطة مدفوعة أولًا لتتمكن من تمديدها أو نقلها.'}</Text>
        <View style={styles.balanceRow}><Text style={styles.balanceValue}>{money(wallet?.balance ?? 0)}</Text><Text style={styles.balanceLabel}>رصيد المحفظة المتاح</Text></View>
      </GlowCard>
      {isPaid ? <><SectionLabel>تمديد الاشتراك</SectionLabel><View style={styles.sectionCard}><Text style={styles.sectionDescription}>اختر إجمالي المدة المستهدفة. سيتم احتساب الأيام الإضافية فقط.</Text>
        <View style={styles.targetRow}>{targets.map(target => { const reached = days >= target; const active = selectedTarget === target; return <Pressable key={target} testID={`subscription-target-${target}`} onPress={() => { setSelectedTarget(target); clearResults(); }} style={[styles.target, active && styles.targetSelected, reached && styles.targetReached]}><Text style={[styles.targetNumber, active && styles.targetSelectedText]}>{target}</Text><Text style={[styles.targetLabel, active && styles.targetSelectedText]}>يوم إجمالي</Text>{reached ? <Text style={styles.covered}>مشمول</Text> : <Text style={styles.added}>+{target - days} يوم</Text>}{active && <Feather name="check" size={14} color="#fff" style={styles.targetCheck} />}</Pressable>; })}</View>
        <Text style={styles.extensionSummary}>{targetReached ? `اشتراكك يتجاوز ${selectedTarget} يومًا حاليًا.` : `سيتم إضافة ${extensionDays} يومًا وخصم ${money(extensionCost)}.`}</Text>{extensionCost > (wallet?.balance ?? 0) && <Text style={styles.warning}>⚠ رصيد المحفظة غير كافٍ لهذه الإضافة.</Text>}
        <PrimaryButton onPress={() => setAction('extend')} disabled={busy || targetReached || extensionCost > (wallet?.balance ?? 0)}>{extensionCost > (wallet?.balance ?? 0) ? 'الرصيد غير كافٍ' : 'مراجعة التمديد'}</PrimaryButton></View>
        <SectionLabel>إجراءات الاشتراك</SectionLabel><Pressable testID="subscription-transfer" onPress={() => setTransferVisible(true)} disabled={busy} style={styles.actionCard}><View style={styles.actionIcon}><Feather name="send" size={18} color="#bdaeff" /></View><View style={styles.actionCopy}><Text style={styles.actionTitle}>نقل الاشتراك</Text><Text style={styles.actionDescription}>انقل الخطة الفعالة إلى حساب LMR آخر</Text></View><Feather name="chevron-left" size={18} color={colors.light.mutedForeground} /></Pressable>
        <Pressable testID="subscription-cancel" onPress={() => setAction('cancel')} disabled={busy} style={[styles.actionCard, styles.dangerCard]}><View style={[styles.actionIcon, styles.dangerIcon]}><Feather name="x-circle" size={18} color="#ff8292" /></View><View style={styles.actionCopy}><Text style={[styles.actionTitle, styles.dangerText]}>إلغاء الاشتراك فورًا</Text><Text style={styles.actionDescription}>سيعود الحساب إلى خطة درويش مباشرة</Text></View><Feather name="chevron-left" size={18} color="#b36d7d" /></Pressable>
      </> : <View style={styles.freeCard}><Feather name="info" size={20} color={colors.light.primary} /><Text style={styles.freeText}>لإدارة التمديد والنقل، اختر خطة مدفوعة من صفحة الخطط.</Text><PrimaryButton onPress={() => router.push('/plans')}>عرض الخطط</PrimaryButton></View>}
      {(extensionResult || cancelResult || transferResult) && <View style={styles.resultCard}><Feather name="check-circle" size={20} color={colors.light.success} /><View style={styles.actionCopy}><Text style={styles.resultTitle}>{extensionResult ? 'تم التمديد بنجاح' : cancelResult ? 'تم الإلغاء بنجاح' : 'تم نقل الاشتراك بنجاح'}</Text><Text style={styles.actionDescription}>{extensionResult ? `أضيفت ${extensionResult.additionalDays} يوم، ورصيدك الآن ${money(extensionResult.balance)}.` : cancelResult ? 'تم تحديث حالة اشتراكك فوراً.' : `تم النقل إلى ${transferResult?.recipient.name || transferResult?.recipient.userId}.`}</Text></View><Pressable onPress={clearResults}><Feather name="x" size={16} color={colors.light.mutedForeground} /></Pressable></View>}
    </>}</ScrollView>
    <Modal visible={transferVisible} transparent animationType="slide" onRequestClose={() => !busy && setTransferVisible(false)}><KeyboardAvoidingView style={styles.modalBackdrop} behavior={Platform.OS === 'web' ? undefined : 'padding'}><View style={[styles.sheet, { paddingBottom: insets.bottom + 18 }]}><View style={styles.handle} /><Text style={styles.sheetTitle}>نقل الاشتراك</Text><Text style={styles.sheetDescription}>أدخل معرّف الحساب المستلم بصيغة LMR-XXXXXXXX.</Text><TextInput testID="subscription-recipient" value={recipient} onChangeText={v => { setRecipient(v); setNotice(null); }} placeholder="LMR-12345678" placeholderTextColor={colors.light.mutedForeground} style={styles.sheetInput} autoCapitalize="characters" autoCorrect={false} editable={!busy} /><PrimaryButton onPress={reviewTransfer} disabled={!recipient.trim()}>متابعة إلى التأكيد</PrimaryButton><Pressable onPress={() => setTransferVisible(false)} disabled={busy} style={styles.closeSheet}><Text style={styles.closeText}>إلغاء</Text></Pressable></View></KeyboardAvoidingView></Modal>
    <Modal visible={action !== null} transparent animationType="fade" onRequestClose={() => !busy && setAction(null)}><View style={styles.modalBackdrop}><View style={styles.confirmSheet}><View style={styles.handle} /><View style={styles.confirmIcon}><Feather name={action === 'cancel' ? 'alert-triangle' : action === 'transfer' ? 'send' : 'credit-card'} size={23} color={action === 'cancel' ? colors.light.destructive : colors.light.primary} /></View><Text style={styles.sheetTitle}>{modalTitle}</Text><Text style={styles.sheetDescription}>{modalDescription}</Text>{action === 'extend' && <View style={styles.summary}><Text style={styles.summaryText}>{extensionDays} يوم  •  {money(extensionCost)}  •  {money(balanceAfter)}</Text></View>}<View style={styles.modalActions}><PrimaryButton secondary onPress={() => setAction(null)} disabled={busy}>مراجعة مرة أخرى</PrimaryButton><PrimaryButton onPress={() => void execute()} disabled={busy}>{busy ? 'جارٍ التنفيذ...' : 'تأكيد التنفيذ'}</PrimaryButton></View></View></View></Modal>
  </ScreenBackground>;
}

const styles = StyleSheet.create({
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 }, loadingText: { color: colors.light.mutedForeground, fontSize: 12 },
  heroCard: { marginHorizontal: 18, gap: 10 }, heroTop: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between' }, heroIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#18366d' }, heroTitle: { color: colors.light.foreground, textAlign: 'right', fontSize: 19, fontWeight: '900' }, heroText: { color: '#c1d2f4', textAlign: 'right', fontSize: 11, lineHeight: 19 }, balanceRow: { flexDirection: 'row-reverse', justifyContent: 'space-between', paddingTop: 7, borderTopWidth: 1, borderTopColor: '#ffffff16' }, balanceValue: { color: '#d1c1ff', fontSize: 15, fontWeight: '900' }, balanceLabel: { color: '#9eb5e2', fontSize: 10 },
  sectionCard: { marginHorizontal: 18, padding: 16, gap: 13, borderRadius: 18, backgroundColor: colors.light.card, borderWidth: 1, borderColor: colors.light.border }, sectionDescription: { color: colors.light.mutedForeground, fontSize: 11, lineHeight: 19, textAlign: 'right' }, targetRow: { flexDirection: 'row-reverse', gap: 8 }, target: { flex: 1, minHeight: 78, alignItems: 'center', justifyContent: 'center', borderRadius: 14, backgroundColor: colors.light.background, borderWidth: 1, borderColor: colors.light.border, position: 'relative' }, targetSelected: { backgroundColor: '#1f4d91', borderColor: colors.light.primary }, targetReached: { borderColor: '#326e65' }, targetNumber: { color: colors.light.foreground, fontSize: 19, fontWeight: '900' }, targetLabel: { color: colors.light.mutedForeground, fontSize: 10 }, targetSelectedText: { color: '#fff' }, targetCheck: { position: 'absolute', top: 7, right: 7 }, covered: { color: colors.light.success, fontSize: 9 }, added: { color: colors.light.mutedForeground, fontSize: 9 }, extensionSummary: { color: '#bcaeff', textAlign: 'right', fontSize: 11 }, warning: { color: '#ffb4a8', textAlign: 'right', fontSize: 10 },
  actionCard: { minHeight: 70, marginHorizontal: 18, marginBottom: 9, paddingHorizontal: 14, flexDirection: 'row-reverse', alignItems: 'center', gap: 12, borderRadius: 16, backgroundColor: colors.light.card, borderWidth: 1, borderColor: colors.light.border }, actionIcon: { width: 38, height: 38, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: '#2a2055' }, actionCopy: { flex: 1 }, actionTitle: { color: colors.light.foreground, fontSize: 13, fontWeight: '800', textAlign: 'right' }, actionDescription: { color: colors.light.mutedForeground, fontSize: 10, textAlign: 'right', marginTop: 4 }, dangerCard: { borderColor: '#54273b', backgroundColor: '#21142a' }, dangerIcon: { backgroundColor: '#4a1d31' }, dangerText: { color: '#ffb0bb' }, freeCard: { margin: 18, padding: 18, alignItems: 'center', gap: 13, borderRadius: 18, backgroundColor: colors.light.card, borderWidth: 1, borderColor: colors.light.border }, freeText: { color: colors.light.mutedForeground, fontSize: 12, lineHeight: 20, textAlign: 'center' },
  notice: { marginHorizontal: 18, marginBottom: 12, padding: 12, flexDirection: 'row-reverse', alignItems: 'center', gap: 9, borderRadius: 14, backgroundColor: '#123d3b', borderWidth: 1, borderColor: colors.light.success }, noticeError: { backgroundColor: '#431d2c', borderColor: colors.light.destructive }, noticeText: { flex: 1, color: colors.light.foreground, fontSize: 11, textAlign: 'right' }, errorCard: { margin: 18, padding: 20, alignItems: 'center', gap: 10, borderRadius: 18, backgroundColor: colors.light.card }, errorTitle: { color: colors.light.foreground, fontSize: 15, fontWeight: '800' }, errorText: { color: colors.light.mutedForeground, textAlign: 'center', fontSize: 11 }, resultCard: { margin: 18, padding: 14, flexDirection: 'row-reverse', alignItems: 'center', gap: 10, borderRadius: 16, backgroundColor: '#123d3b', borderWidth: 1, borderColor: colors.light.success }, resultTitle: { color: colors.light.success, textAlign: 'right', fontWeight: '800', fontSize: 13 },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.68)' }, sheet: { padding: 20, borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: '#0d1733', borderWidth: 1, borderColor: colors.light.border, gap: 13 }, confirmSheet: { margin: 18, padding: 20, borderRadius: 24, backgroundColor: '#0d1733', borderWidth: 1, borderColor: colors.light.border, gap: 13 }, handle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 2, backgroundColor: '#53658e', marginBottom: 6 }, confirmIcon: { alignSelf: 'center', width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.light.secondary }, sheetTitle: { color: colors.light.foreground, fontSize: 19, fontWeight: '800', textAlign: 'right' }, sheetDescription: { color: colors.light.mutedForeground, fontSize: 11, lineHeight: 19, textAlign: 'right' }, sheetInput: { height: 52, borderRadius: 14, backgroundColor: colors.light.background, borderWidth: 1, borderColor: colors.light.border, color: colors.light.foreground, textAlign: 'left', paddingHorizontal: 14, letterSpacing: 1 }, closeSheet: { alignItems: 'center', padding: 8 }, closeText: { color: colors.light.mutedForeground, fontSize: 12 }, summary: { padding: 13, borderRadius: 12, backgroundColor: colors.light.secondary }, summaryText: { color: colors.light.foreground, textAlign: 'center', fontSize: 11, fontWeight: '700' }, modalActions: { flexDirection: 'row-reverse', gap: 9 },
});